config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root to: 'pages#home'
  # get "test", to: "pages#test"

  resources :users, only: [:show, :update]

  get 'user_edit', to: 'users#edit'

  resources :matches

  resources :user_events, only:[:index]

  resources :groups

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :creater, class_name: 'User'

  validates :name, presence: true

  def members
    user_ids.map do |user_id|
      User.find(user_id)
    end
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = Group.all
    @groups_creater = Group.where(creater_id: current_user.id)
    @groups_member = @groups.select { |g| g.members.include?(current_user) }
    @my_groups = @groups_creater + @groups_member
  end

  def show; end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.creater_id = current_user.id

    @group.save
    redirect_to groups_path
  end

  def update
    @group.update(group_params)
    redirect_to groups_path
  end

  def destroy
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    returned_params = params
                      .require(:group).permit(:name)
    if params[:group][:user_ids].present?
      returned_params = returned_params.merge(user_ids: JSON.parse(params[:group][:user_ids]))
    end
    returned_params
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/views/groups/edit.html.erb
<div id="wrapper" class="background-green-white">

  <div class="container">

    <% possible_users = (User.all - [current_user]) %>

    <div id='possible_users' data-input-id="group_user_ids" data-users='<%= (possible_users).to_json %>'> <% possible_users %> </div>

    <div id='edit-group'>

      <%= simple_form_for @group do |f| %>

        <%= f.error_notification %>

        <div class="name-container">

          <%= f.input :name, label: "Name", placeholder: 'Family diner', input_html: { class: 'name-input' } %>

          <div id="name-error" class="error-message">

            <p>Please put a name</p>

          </div>

        </div>

        <div class="members-container">

          <%= f.input :user_ids, as: :hidden %>

          <div class="custom-dropdown">

            <div id="attendee-div" class="form-group">

              <label for="shown_user">Select the members</label>

              <div>

                <span id="user-icon" class="fa fa-user user-icon"></span>

              </div>

              <input type="text" id="shown_user_ids" autocomplete="off">

            </div>

            <div id="user_search_results" class="inactif">

              <% possible_users.each do |user| %>

              <p class='user' data-user-id="<%= user.id %>"><%= user.email %> <i class="fas fa-plus"></i></p>

              <% end %>

            </div>

            <div id="attendee-error-message" class="error-message">

              <p>Please select at least one friend</p>

            </div>

          </div>

          <div id="selected_user_ids" style="display: flex; flex-wrap: wrap;" data-group="<%= @group.user_ids.to_json%>">

          </div>


        </div>

        <div class="button-edit-group">

          <%= f.button :submit, 'Edit', class: "button", id: "button-edit-group" %>

        </div>

      <% end %>

    </div>

  </div>

</div>

app/views/groups/index.html.erb
<div id="wrapper" class="background-green-white">

  <div class="container my-groups-page-container">

    <div class="my-groups-page">

      <% if @my_groups == [] %>

        <div class="no-group">

          <h3>You don't have any group yet</h3>

          <div>

            <%= link_to new_group_path, class: "add-something" do %>

              <i class="fas fa-plus"></i> Create your first group

            <% end %>

          </div>

        </div>

      <% else %>

        <div class="add-something-when-groups">

          <%= link_to new_group_path, class: "add-something" do %>

            New group <i class="fas fa-plus"></i>

          <% end %>

        </div>

        <div class="card-index">

          <% @my_groups.uniq.each do |group| %>

            <div class="group-card">

              <div class="top">

                <h3><%= group.name.capitalize %></h3>

                <img src="<%= group.creater.avatar %>" class="card-trip-user" />

              </div>

              <div class="medium">

                <div class="group-member-layout">

                  <% group.members.each do |user| %>

                    <div class="member_each">

                      <img src="<%= user.avatar %>" class="card-trip-user" />

                      <p><%= user.email %></p>

                    </div>

                  <% end %>

                </div>

              </div>

              <div class="bottom">

                <% if group.creater_id == current_user.id %>

                  <p class="group-links">

                    <%= link_to new_match_path(group_id: group.id), class: "icon" do %>

                      <i class="far fa-calendar-check"></i>

                    <% end %>

                    <%= link_to edit_group_path(group), class: "icon" do %>

                      <i class="fas fa-user-edit"></i>

                    <% end %>

                    <%= link_to group_path(group), method: :delete, data: { confirm: "Are you sure?" }, class: "icon" do %>

                      <i class="fas fa-trash-alt"></i>

                    <% end %>

                  </p>

                <% end %>

              </div>

            </div>

          <% end %>

        </div>

      <% end %>

    </div>

  </div>

</div>

app/views/groups/new.html.erb
<% possible_users = (User.all - [current_user]) %>

<div id='possible_users' data-input-id="group_user_ids" data-users='<%= (possible_users).to_json %>'> <% possible_users %> </div>

<div id="wrapper" class="background-green-white">

  <div class="container">

    <div id='create-group'>

      <%= simple_form_for @group do |f| %>

        <%= f.error_notification %>

        <div class="name-container">

          <%= f.input :name, label: "Name", placeholder: 'Family diner', input_html: { class: 'name-input' } %>

          <div id="name-error" class="error-message">

            <p>Please put a name</p>

          </div>

        </div>

        <div class="members-container">

          <%= f.input :user_ids, as: :hidden %>

          <div class="custom-dropdown">

            <div id="attendee-div" class="form-group">

              <label for="shown_user">Select the members</label>

              <div>

                <span id="user-icon" class="fa fa-user user-icon"></span>

              </div>

              <input type="text" id="shown_user_ids" autocomplete="off">

            </div>

            <div id="user_search_results" class="inactif">

              <% possible_users.each do |user| %>

              <p class='user' data-user-id="<%= user.id %>"><%= user.email %> <i class="fas fa-plus"></i></p>

              <% end %>

            </div>

            <div id="attendee-error-message" class="error-message">

              <p>Please select at least one friend</p>

            </div>

          </div>

          <div id="selected_user_ids" style="display: flex; flex-wrap: wrap;">

          </div>

        </div>

        <div class="button-create-group">

          <%= f.button :submit, 'Create group', class: "button", id: "button-create-group" %>

        </div>

      <% end %>

    </div>

  </div>

</div>