config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root to: 'pages#home'
  # get "test", to: "pages#test"

  resources :users, only: [:show, :update]

  get 'user_edit', to: 'users#edit'

  resources :matches

  resources :user_events, only:[:index]

  resources :groups

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<%# Mobile size %>

<div id="mobile-size">

  <% if user_signed_in? %>

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-iphone">

      <div class="navbar-top">

        <%= link_to root_path, class: "brand-button" do %>

          <div class="root-navbar-button">

            <%= image_tag "CalendarMatcher.svg", :class => "icon-cm", :id => "logo-image"%>

          </div>

          <div class="root-navbar-title">

            <h1>Calendar Matcher</h1>

          </div>

        <% end %>

        <div class="navbar-top-right">

          <% if !current_page?(root_url) %>

            <% if request.path_info.exclude?('matches/new') %>

              <% if !current_page?(matches_path) %>

                <%= link_to new_match_path, class: "navbar-new-event-top-right" do %>

                  <%= image_tag "plus.svg", class: "create-event-button-exclude-home-and-new-match" %>

                <% end %>

              <% end %>

            <% end %>

          <% end %>

          <ul class="my-account-dropdown">

            <li class="nav-item dropdown">

              <% if current_user.avatar != nil %>

                <%= image_tag "#{current_user.avatar}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

              <% else %>

                <%= image_tag "empty-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

              <% end %>

              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                <%= link_to "My Calendar", user_events_path, class: "dropdown-item"  %>

                <%= link_to "My Groups", groups_path, class: "dropdown-item" %>

                <% if current_page?(matches_path) %>

                  <%= link_to "My events", matches_path, class: "dropdown-item" %>

                <% else %>

                  <%= link_to "My events", matches_path, class: "dropdown-item" %>

                <% end %>

                <%= link_to "My account", user_path(current_user), class: "dropdown-item" %>

                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item", id: "log-out-button" %>

              </div>

            </li>

          </ul>

        </div>

      </div>

      <ul class="navbar-nav navigator">

        <li class="nav-item active">

          <div class="navigation-link">

            <% if current_page?(root_path) %>

            <% elsif current_page?(new_match_path) %>

              <div class="what-path-i-am-on">Create an event</div>

            <% elsif current_page?(matches_path) %>

              <div class="what-path-i-am-on">My events</div>

            <% elsif current_page?(user_events_path) %>

              <div class="what-path-i-am-on">My calendar</div>

            <% elsif current_page?(groups_path) %>

              <div class="what-path-i-am-on">My groups</div>

            <% elsif current_page?(new_group_path) %>

              <div class="what-path-i-am-on">New group</div>

            <% elsif request.path_info.include?('groups/') %>

              <div class="what-path-i-am-on">Edit my group</div>

            <% elsif request.path_info.include?('users/') %>

              <div class="what-path-i-am-on">My account</div>

            <% elsif request.path_info.include?('user_edit') && current_user.settings == false %>

              <div class="what-path-i-am-on">Create my account</div>

            <% elsif request.path_info.include?('user_edit') %>

              <div class="what-path-i-am-on">Edit my account</div>

            <% elsif request.path_info.include?("matches/#{@match.id}/edit") %>

              <div class="what-path-i-am-on">Edit my event</div>

            <% end %>

          </div>

        </li>

      </ul>

    </div>

  <% else %>

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-lewagon-not-connected">

        <%= link_to root_path, class: "navbar-lewagon-not-connected-top-left" do %>

          <%= image_tag "CalendarMatcher.svg", :class => "navbar-brand-button-not-connected"%>

          <div class="navbar-brand-title-not-connected">

            <h1>Calendar Matcher</h1>

          </div>

        <% end %>

      <%= link_to "Log in with Google", user_google_oauth2_omniauth_authorize_path, class: "button-login" %>

    </div>

  <% end %>

</div>

<%# Computer size %>

<div id="computer-size">

  <% if user_signed_in? %>

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

      <% if current_page?(user_edit_path) && current_user.settings == false %>

        <div class="brand-button">

          <div class="root-navbar-button">

            <%= image_tag "CalendarMatcher.svg", :class => "icon-cm", :id => "logo-image"%>

          </div>

          <div class="root-navbar-title">

            <h1>Calendar Matcher</h1>

          </div>

        </div>

      <% else %>

        <%= link_to root_path, class: "brand-button" do %>

          <div class="root-navbar-button">

            <%= image_tag "CalendarMatcher.svg", :class => "icon-cm", :id => "logo-image"%>

          </div>

          <div class="root-navbar-title">

            <h1>Calendar Matcher</h1>

          </div>

        <% end %>

      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

        <span class="navbar-toggler-icon"></span>

      </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <ul class="navbar-nav mr-auto">

            <% if user_signed_in? %>

              <% if current_page?(user_edit_path) && current_user.settings == false %>

                <li class="nav-item active">

                  <div class="navigation-links">

                    <% if request.path_info.include?('matches/')  %>

                      <%= link_to "Create an event", new_match_path, class: "if-create-path" %>

                    <% else %>

                      <div class="nav-link-create">Create an event</div>

                    <% end %>

                    <div class="nav-link login_hover">My Calendar</div>

                    <div class="nav-link active-nav login_hover">My Groups</div>

                    <% if current_page?(matches_path) %>

                      <%= link_to "My events", matches_path, class: "nav-link nav-link-my-events active-nav" %>

                    <% else %>

                      <div class="nav-link active-nav">My events</div>

                    <% end %>

                  </div>

                </li>

                <li class="nav-item dropdown">

                  <% if current_user.avatar != nil %>

                    <%= image_tag "#{current_user.avatar}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

                  <% else %>

                    <%= image_tag "empty-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

                  <% end %>

                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                    <div class="dropdown-item">My account</div>

                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item",id: "log-out-button" %>

                  </div>

                </li>

              <% else %>

                <li class="nav-item active">

                  <div class="navigation-links">

                    <% if current_page?(root_path) %>

                    <% else %>

                      <% if current_page?(matches_path) %>

                      <% elsif current_page?(new_match_path) %>

                        <%= link_to "Create an event", new_match_path, class: "nav-link what-path-i-am-on" %>

                      <% else %>

                        <%= link_to "Create an event", new_match_path, class: "nav-link-create" %>

                      <% end %>

                    <% end %>

                    <%= link_to "My Calendar", user_events_path, class: "nav-link login_hover #{controller.controller_name == "user_events" ? "active_nav" : "nothing"}"  %>

                    <%= link_to "My Groups", groups_path, class: "nav-link active-nav login_hover #{controller.controller_name == "groups" ? "active_nav" : "nothing"}" %>

                    <% if current_page?(matches_path) %>

                      <%= link_to "My events", matches_path, class: "nav-link nav-link-my-events active-nav" %>

                    <% else %>

                      <%= link_to "My events", matches_path, class: "nav-link active-nav" %>

                    <% end %>

                  </div>

                </li>

                <li class="nav-item dropdown">

                  <% if current_user.avatar != nil %>

                    <%= image_tag "#{current_user.avatar}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

                  <% else %>

                    <%= image_tag "empty-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

                  <% end %>

                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                    <%= link_to "My account", user_path(current_user), class: "dropdown-item" %>

                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item",id: "log-out-button" %>

                  </div>

                </li>

              <% end %>

            <% end %>

          </ul>

        </div>

    </div>

  <% else %>

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-lewagon-not-connected">

      <div class="title-brand">

        <%= link_to root_path, class: "navbar-brand-button-not-connected" do %>

          <div>

            <%= image_tag "CalendarMatcher.svg", :class => "icon-cm"%>

          </div>

        <% end %>

        <%= link_to root_path, class: "navbar-brand-title-not-connected" do %>

          <h1>Calendar Matcher</h1>

        <% end %>

      </div>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">

            <li class="nav-item-not-connected">

              <%= link_to "Log in with Google", user_google_oauth2_omniauth_authorize_path, class: "button-login" %>

            </li>

        </ul>

      </div>

    </div>

  <% end %>

</div>