config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root to: 'pages#home'
  # get "test", to: "pages#test"

  resources :users, only: [:show, :update]

  get 'user_edit', to: 'users#edit'

  resources :matches

  resources :user_events, only:[:index]

  resources :groups

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
# frozen_string_literal: true

class Match < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :owner, class_name: 'User'

  validates :title, presence: true
  validates :max_date, presence: true
  validates :user_ids, presence: true

  validates :min_timem, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 60 }
  validates :max_timem, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 60 }
  validates :min_timeh, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 25 }
  validates :max_timeh, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 25 }


  def attendees
    user_ids.map do |user_id|
      User.find(user_id)
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[show edit update destroy]

  def index
    @validated = Match.find_by(id: params[:validated_id])
    @my_events = Match.joins(:users).where(owner_id: current_user.id).or(
      Match.joins(:users).where('users.id': current_user.id)
    ).where.not(match_date: nil).order(match_date: :desc).distinct
  end

  def show
    @results = FindMatch.date(@match.id, @match.owner_id, @match.user_ids, @match.min_time, @match.max_time, @match.max_date, @match.min_date)
  end

  def new
    @match = Match.new

    group = Group.find_by_id(params['group_id'])

    @group_user_ids = group.present? ? group.users.where.not(id: current_user.id).ids : []
  end

  def create
    # 1. verifier s'il faut creer un groupe

    if group_params[:create_group]
      @group = Group.new
      @group.name = group_params[:group_name]
      @group.creater_id = current_user.id
      @group.user_ids = match_params[:user_ids]
      @group.save
    end

    # 2. creer le match sans date finale !!!
    @match = Match.new(match_params)

    # set min_time and max_time with the correct time zone of the user
    a = params[:match]

    min_time_TZ = DateTime.new(Time.now.strftime("%Y").to_i,Time.now.strftime("%m").to_i,Time.now.strftime("%d").to_i,a["min_timeh"].to_i,a["min_timem"].to_i, 0 ,Time.now.zone)
    max_time_TZ = DateTime.new(Time.now.strftime("%Y").to_i,Time.now.strftime("%m").to_i,Time.now.strftime("%d").to_i,a["max_timeh"].to_i,a["max_timem"].to_i, 0 ,Time.now.zone)
    @match.min_time = min_time_TZ
    @match.max_time = max_time_TZ

    @match.group_id = @group.id if @group

    @match.owner_id = current_user.id
    if @match.save
      redirect_to match_path(@match)
    else
      render :new
    end
  end

  def edit
     @group_user_ids =[]
  end

  def update
    if @match.update(match_params)

      if request.env["HTTP_REFERER"]=="http://localhost:3000/matches/#{@match.id}/edit" || request.env["HTTP_REFERER"]=="www.calendarmatcher.com/matches/#{@match.id}/edit"
        SendInvitation.update_google_event(@match, current_user)
        p("heloo")
        redirect_to :controller => 'matches', :action => 'index'
        p("salut")

      else
        respond_to do |format|
          format.json { render json: @match.as_json }
        end
      end

    end
  end

  def destroy
    @match.destroy
    redirect_to matches_path
  end

  private

  def match_params
    returned_params = params
                      .require(:match).permit(:id, :title, :description,
                        :location, :match_date, :min_date, :max_date,
                        :min_timeh, :min_timem, :max_timeh, :max_timem,
                        :state, :owner_id, :group_id)
    if params[:match][:user_ids].present?
      returned_params = returned_params.merge(user_ids: JSON.parse(params[:match][:user_ids]))
    end
    returned_params
  end

  def group_params
    params.permit(:group_name, :create_group)
  end

  def set_match
    @match = Match.find(params[:id])
  end

end

app/views/matches/edit.html.erb
<div id="wrapper" class="background-green-white">

  <div class="container">

    <% possible_users = (User.all - [current_user]) %>

    <div id='possible_users' data-input-id="match_user_ids" data-users='<%= (possible_users).to_json %>'> <% possible_users %> </div>

    <div id='edit-event'>

      <div class="form">

        <%= simple_form_for @match do |f| %>

          <div class="title-container">

            <%= f.input :title, label: 'Title of the event :', input_html: { class: 'title-input' } %>

            <div id="title-error" class="error-message">

              <p>Please put a title</p>

            </div>

          </div>

          <%= f.input :location, label: 'Address of the event :' %>

          <%= f.input :description, label: 'Description :' %>

          <p class="current-match-date"><%= "The current match date is #{@match.max_date}" %></p>

          <p class="date-label">You want your event to happen between :</p>

          <div class="date-container">

            <div class="min_date">

              <%= f.input :min_date, as: :date, html5: true, label: 'Min date *', input_html: { class: 'date-min-input' } %>

              <div id="date-min-error" class="date-min-error-message">

                <p>Hey i'm Yann</p>

              </div>

              <div id="date-min-error-2" class="error-message">

                <p>Please put a minimum date above today's date</p>

              </div>

            </div>

            <div class="max_date">

              <%= f.input :max_date, as: :date, html5: true, label: 'Max date', input_html: { class: 'date-max-input' } %>

              <div id="date-max-error" class="error-message">

                <p>Please put a maximum date</p>

              </div>

              <div id="date-max-error-2" class="error-message">

                <p>Please put a maximum date above minimum date</p>

              </div>

            </div>

          </div>

          <p class="hours-label">You want your event to happen from :</p>

          <div class="hours-container">

            <div class="hours-container-1">

              <p class="hours-label-1">Min hour *</p>

              <div class="hours-mins-container-1">

                <%= f.input :min_timeh, label: false, placeholder: "19", input_html: { min: '0', max: '24', step: '1' }, input_html: { class: 'hour-min-input', maxlength: 2 }%>

                <p id="double-point-min" class="double-point">:</p>

                <%= f.input :min_timem, label: false, placeholder:"30", input_html: { min: '0', max: '59', step: '1' }, input_html: { class: 'min-min-input', maxlength: 2 }%>

              </div>

              <div id="hour-min-invalid" class="error-message">

                  <p>Please put a valid minimum hour</p>

              </div>

              <div id="right-hour" class="error-message">

                  <p>Min hour must be lower than hour max</p>

              </div>

            </div>

            <div class="hours-container-2">

                <div>

                  <p class="hours-label-2">Max hour *</p>

                </div>

                <div class="hours-mins-container-2">

                  <%= f.input :max_timeh, label: false, placeholder:"22", input_html: { min: '0', max: '24', step: '1' }, input_html: { class: 'hour-max-input', maxlength: 2 } %>

                  <p id="double-point-max" class="double-point">:</p>

                  <%= f.input :max_timem, label: false, placeholder:"30", input_html: { min: '0', max: '24', step: '1' }, input_html: { class: 'min-max-input', maxlength: 2 } %>

                </div>

                <div id="hour-max-invalid" class="error-message">

                  <p>Please put a valid maximum hour</p>

                </div>

            </div>

          </div>

          <div class="custom-dropdown">

            <div id="attendee-div" class="form-group">

              <label for="shown_user">Select the attendees : *</label>

              <div>

                <span id="user-icon" class="fa fa-user user-icon"></span>

              </div>

              <input type="text" id="shown_user_ids" autocomplete="off">

            </div>

            <div id="user_search_results" class="inactif">

                <% possible_users.each do |user| %>

                <p class='user' data-user-id="<%= user.id %>"><%= user.email%> <i class="fas fa-plus"></i></p>

                <% end %>

            </div>

            <div id="attendee-error-message" class="error-message">

              <p>Please select at least one friend</p>

            </div>

          </div>

          <div id="selected_user_ids" style="display: flex; flex-wrap: wrap;" data-attendees="<%= @match.user_ids.to_json %>">

          </div>

          <% if @match.errors.present? %>

            <p class="attendee_error_msg"> <%= @match.errors[:user_ids][0] %> </p>

          <% end %>

          <%= f.input :user_ids, as: :hidden %>

          <% if group = Group.find_by_id(params['group_id']) %>

          <% else %>

            <%= check_box_tag "create_group", 'create_group' %>

            <%= label_tag "Create a new group ?" %>

            <%= text_field_tag :group_name, nil, placeholder: '  Family' %>

          <% end %>

          <div class="button-edit-match">

            <%= f.button :submit, 'Edit', class:"button", id:"button-edit-the-match" %>

          </div>


        <% end %>

      </div>

    </div>

  </div>

</div>

app/views/matches/index.html.erb
<div id="wrapper" class="background-green-white">

  <div class="container my-events-page-container">

    <div class="my-events-page">

      <% if @my_events == [] %>

        <div class="no-event">

          <h3>You don't have any event yet</h3>

          <div>

            <%= link_to new_match_path, class: "add-something" do %>

              <i class="fas fa-plus"></i> Create your first event

            <% end %>

          </div>

        </div>

      <% else %>

        <div class="add-something-when-events">

          <%= link_to new_match_path, class: "add-something" do %>

            New event <i class="fas fa-plus"></i>

          <% end %>

        </div>

        <% if @my_events.count == 1 %>

          <div class="card-index-alone">

        <% else %>

          <div class="card-index">

        <% end %>

          <% @my_events.each do |match| %>

            <div class="event-card">

              <div class="top">

                <h3><%= match.title.capitalize %></h3>

                <img src="<%= match.owner.avatar %>" class="card-trip-user avatar-bordered" />

              </div>

              <div class="event-info">

                <% if match.match_date == nil %>

                  <p class="event-date-not-found">Still looking for a match</p>

                <% else %>

                  <div class="event-date">

                    <p><%= "#{match.match_date.strftime("%a %d %B %Y")}" %></p>

                    <p><%= " from #{match.min_time.localtime.strftime("%H:%M")} until #{match.max_time.localtime.strftime("%H:%M")}" %></p>

                  </div>

                <% end %>

                <% if match.location != "" %>

                  <div class="event-location">

                    <p><b>Location :</b></p>

                    <p><%= match.location %></p>

                  </div>

                <% end %>

                <% if match.description != "" %>

                  <div class="event-description">

                    <p><b>Description :</b></p>

                    <p><%= match.description %></p>

                  </div>

                <% end %>

              </div>

              <div class="medium-event-title">

                <p class="event-attendees"><b>Attendees :</b></p>

                <div class="medium">

                  <div class="event-member-layout">

                    <% match.attendees.each do |user| %>

                      <div class="member_each">

                        <img src="<%= user.avatar %>" class="card-trip-user" />

                        <p><%= user.email %></p>

                      </div>

                    <% end %>

                  </div>

                </div>

              </div>

              <div class="bottom">

                <% if match.owner_id == current_user.id  %>

                  <p class="group-links">

                    <%= link_to edit_match_path(match) do %>

                      <i class="icon fas fa-pencil-alt"></i>

                    <% end %>

                    <%= link_to match_path(match), method: :delete, data: { confirm: "Are you sure?" } do %>

                      <i class="icon fas fa-trash-alt"></i>

                    <% end %>

                  </p>

                <% end %>

              </div>

            </div>

          <% end %>

        </div>

      <% end %>

      <% if @validated %>

        <% SendInvitation.create_google_event(@validated,current_user) %>

        <div id="backpopup" class="backpopup"></div>

        <div id="frontpopup" class="flash flash-successalert-dismissible fade show" role="alert">

          <span id="frontpopupwrittings" class="confirmation-alert"> 🎉 <strong>Yay !</strong> 🎉 </br></br> You successfully created <b><%= @validated.title %></b></br> on the <b><%= @validated.match_date.strftime("%d-%m-%Y")  %></b> from <b><%= @validated.min_time.localtime.strftime("%H:%M") %></b> to <b><%= @validated.max_time.localtime.strftime("%H:%M") %></b> ! </br></br> Invitations have been sent to the attendees.</span>

          <a data-dismiss="alert" aria-label="Close">

            <i class="clickme fas fa-times"></i>

          </a>

        </div>

      <% end %>

</div>

app/views/matches/new.html.erb
<div id="wrapper" class="background-green-white">

  <div class="container">

    <% possible_users = (User.all - [current_user]) %>

    <div id='possible_users' data-input-id="match_user_ids" data-users='<%= (possible_users).to_json %>'> <% possible_users %> </div>

    <div id='create-event'>

      <div class="form">

        <%= simple_form_for @match do |f| %>

          <div class="title-container">

            <%= f.input :title, label: 'Title of the event :', placeholder: 'Family diner', input_html: { class: 'title-input' } %>

            <div id="title-error" class="error-message">

              <p>Please put a title</p>

            </div>

          </div>

          <%= f.input :location, label: 'Address of the event :', placeholder: '29 rue du bondinner' %>

          <%= f.input :description, label: 'Description :', placeholder: "Bring some desserts and don't be late" %>

          <p class="date-label">You want your event to happen between :</p>

          <div class="date-container">

            <div class="min_date">

            <%# try to implement a placeholder here with "DateTime.now.strftime("%d/%m/%Y")" %>

              <%= f.input :min_date, as: :date, html5: true, label: 'Min date *', input_html: { class: 'date-min-input' } %>

              <div id="date-min-error" class="date-min-error-message">

                <p>Hey i'm Yann L.</p>

              </div>

              <div id="date-min-error-2" class="error-message">

                <p>Please put a minimum date greater than today's date</p>

              </div>

            </div>

            <div class="max_date">

              <%= f.input :max_date, as: :date, html5: true, label: 'Max date', input_html: { class: 'date-max-input' } %>

              <div id="date-max-error" class="error-message">

                <p>Please put a maximum date</p>

              </div>

              <div id="date-max-error-2" class="error-message">

                <p>Please put a maximum date above minimum date</p>

              </div>

            </div>

          </div>

          <p class="hours-label">You want your event to happen from :</p>

          <div class="hours-container">

            <div class="hours-container-1">

              <p class="hours-label-1">Min hour *</p>

              <div class="hours-mins-container-1">

                <%= f.input :min_timeh, label: false, placeholder: "19", input_html: { min: '0', max: '24', step: '1' }, input_html: { class: 'hour-min-input', maxlength: 2 }%>

                <p id="double-point-min" class="double-point">:</p>

                <%= f.input :min_timem, label: false, placeholder:"30", input_html: { min: '0', max: '59', step: '1' }, input_html: { class: 'min-min-input', maxlength: 2 }%>

              </div>

              <div id="hour-min-invalid" class="error-message">

                  <p>Please put a valid minimum hour</p>

              </div>

              <div id="right-hour" class="error-message">

                  <p>Min hour must be lower than hour max</p>

              </div>

            </div>

            <div class="hours-container-2">

                <div>

                  <p class="hours-label-2">Max hour *</p>

                </div>

                <div class="hours-mins-container-2">

                  <%= f.input :max_timeh, label: false, placeholder:"22", input_html: { min: '0', max: '24', step: '1' }, input_html: { class: 'hour-max-input', maxlength: 2 } %>

                  <p id="double-point-max" class="double-point">:</p>

                  <%= f.input :max_timem, label: false, placeholder:"30", input_html: { min: '0', max: '24', step: '1' }, input_html: { class: 'min-max-input', maxlength: 2 } %>

                </div>

                <div id="hour-max-invalid" class="error-message">

                  <p>Please put a valid maximum hour</p>

                </div>

            </div>

          </div>

          <div class="custom-dropdown">

            <div id="attendee-div" class="form-group">

              <label for="shown_user">Select the attendees : *</label>

              <div>

                <span id="user-icon" class="fa fa-user user-icon"></span>

              </div>

              <input type="text" id="shown_user_ids" autocomplete="off">

            </div>

            <div id="user_search_results" class="inactif">

                <% possible_users.each do |user| %>

                <p class='user' data-user-id="<%= user.id %>"><%= user.email%> <i class="fas fa-plus"></i></p>

                <% end %>

            </div>

            <div id="attendee-error-message" class="error-message">

              <p>Please select at least one friend</p>

            </div>

          </div>

          <div id="selected_user_ids" style="display: flex; flex-wrap: wrap;" data-group="<%= @group_user_ids.to_json %>">

          </div>

          <% if @match.errors.present? %>

            <p class="attendee_error_msg"> <%= @match.errors[:user_ids][0] %> </p>

          <% end %>

          <%= f.input :user_ids, as: :hidden %>

          <% if group = Group.find_by_id(params['group_id']) %>

            <%= f.hidden_field :group_id, :value => group.id %>

          <% else %>

            <%= check_box_tag "create_group", 'create_group' %>

            <%= label_tag "Create a group :" %>

            <%= text_field_tag :group_name, nil, placeholder: '  Family' %>

          <% end %>

          <div class="button-create-match">

            <%= f.button :submit, 'Match us', class:"button", id:"button-find-the-match" %>

          </div>

        <% end %>

      </div>

    </div>

  </div>

</div>

app/views/matches/show.html.erb
<div id="wrapper" class="background-green-white">

  <div class="container">

    <div class="new-match-calendar">

      <div class="my-calendar">

        <div
          id="calendar_matches"
          data-ids="<%= current_user.email %>"
          data-results="<%= @results.to_json %>"
          data-matchid="<%= @match.id.to_json%>"
          class="container"
        >

      </div>

    </div>

  </div>

</div>